// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(patterns) {
    var cb, match, pattern, request;
    request = process.argv.slice(2).join(" ");
    for (pattern in patterns) {
      cb = patterns[pattern];
      match = (new RegExp(pattern)).exec(request);
      if (match == null) {
        continue;
      }
      cb.apply(null, match.slice(1, 1 + cb.length));
      return;
    }
    return typeof patterns.help === "function" ? patterns.help(request) : void 0;
  };

}).call(this);
